version: '3.9'
services:
  opensearch-node1:
    #<<: *opensearch-common
    # image: opensearchproject/opensearch:latest
    build: .
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      # - cluster.name=opensearch-cluster
      # - node.name=opensearch-node1
      # - discovery.seed_hosts=opensearch-node1,opensearch-node2
      # - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
    container_name: opensearch-node1
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      # - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      # - ./certs/node.pem:/usr/share/opensearch/config/node.pem
      # - ./certs/node-key.pem:/usr/share/opensearch/config/node-key.pem
      # - ./certs/admin.pem:/usr/share/opensearch/config/admin.pem
      # - ./certs/admin-key.pem:/usr/share/opensearch/config/admin-key.pem
      # - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      # - ./config/securityconfig.yml:/usr/share/opensearch/securityconfig/config.yml
      # - ./config/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      # - ./config/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
      # - ./config/tenants.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/tenants.yml
      # - ./config/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
      # - ./config/action_groups.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml
  # opensearch-node2:
  #   # image: opensearchproject/opensearch:latest
  #   build: .
  #   container_name: opensearch-node2
  #   environment:
  #     - cluster.name=opensearch-cluster
  #     - node.name=opensearch-node2
  #     - discovery.seed_hosts=opensearch-node1,opensearch-node2
  #     - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
  #     - bootstrap.memory_lock=true
  #     - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - DISABLE_INSTALL_DEMO_CONFIG=true
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   volumes:
  #     - opensearch-data2:/usr/share/opensearch/data
  #     # - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
  #     # - ./certs/node.pem:/usr/share/opensearch/config/node.pem
  #     # - ./certs/node-key.pem:/usr/share/opensearch/config/node-key.pem
  #     # - ./certs/admin.pem:/usr/share/opensearch/config/admin.pem
  #     # - ./certs/admin-key.pem:/usr/share/opensearch/config/admin-key.pem
  #     # - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
  #     # - ./config/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
  #     # - ./config/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
  #     # - ./config/tenants.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/tenants.yml
  #     # - ./config/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
  #     # - ./config/action_groups.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml
  #   networks:
  #     - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    # ports:
    #   - 5601:5601
    # expose:
    #   - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
      SERVER_BASEPATH: /kibana
      SERVER_REWRITEBASEPATH: "true"
    volumes:
      - ./config/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    networks:
      - opensearch-net
  nginx:
    build:
      context: ./nginx_conf/
    ports:
      - 80:80
    networks:
      - opensearch-net
  postgres:
    image: postgres:13
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    # healthcheck:
    #   test: ["CMD", "pg_isready"]
    restart: always
    networks:
      - opensearch-net
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["-Dkeycloak.frontendUrl=http://localhost/auth"]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
#      KEYCLOAK_LOGLEVEL: DEBUG
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
      - 8443:8443
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak:8080/auth"]
      retries: 3
    restart: always
    depends_on:
      - postgres
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  keycloak_postgres_data:

networks:
  opensearch-net: